### Upload file
POST http://localhost:8081/attach/upload
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg2NzUxMDIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDg3NjE1MDIsImlzcyI6IllvdVR1YmUifQ.HWkGR7e0N5qJqI3-hi46vOFPCBOouszpBo5i59dZXjS7jo04zveS2XQjxYUodilhfjqPxI3IVuBKe_pJvOXwUA
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.mp4"

< C:\test.mp4

### open
GET http://localhost:8081/attach/open/ef078768-7bc6-4bbb-8f80-1fe8b7298ec4.mp4

### download
GET localhost:8081/attach/download/ef078768-7bc6-4bbb-8f80-1fe8b7298ec4.mp4

### Delete
DELETE localhost:8080/attach/delete/c45b17bd-8eb9-46a7-8507-83f0b8e946e8.mp4


