### registration for email
POST localhost:8081/auth/registration
Content-Type: application/json
Accept-Language: uz

{
  "name": "Ali",
  "surname": "ali",
  "email": "uchanl10@gmail.com",
  "password": "1234"
}

### login
POST localhost:8081/auth/login
Content-Type:application/json
Accept-Language: uz

{
  "email": "jamol3904@gmail.com",
  "password": "1234"
}