### create channel
POST localhost:8081/channel/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyNzU2NTYsImVtYWlsIjoiamFtb2wzOTA0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDkzNjIwNTYsImlzcyI6IllvdVR1YmUifQ.oTzhYHWshacVMWSRiLudUUS09cTqiglchhdXof2xFkCAlKzG_-ewrrrJLfC0TE3l7tBzv-nzJTznmYRqjbPlTA
Content-Type:application/json

{
  "name": "Games",
  "photoId": "982e3c8c-7af9-428f-8040-c9a92af62768",
  "description": "test",
  "bannerId": "982e3c8c-7af9-428f-8040-c9a92af62768",
  "profileId": 5
}

### update channel
PUT localhost:8081/channel/update/191d4771-0dbb-43ae-ac9a-e9dd647a3f26
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5MjY0OTIsImVtYWlsIjoiamFtb2wzOTA0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDkwMTI4OTIsImlzcyI6IllvdVR1YmUifQ.p3m_postr3wLoUlUYWaS-7Q8R_aUVh_r11-702RZQ_DszDQ_LEj_KM6ssFFM3dnKGXY-Wrbo8Fy1_f-rIFiIlA
Content-Type: application/json

{
  "name": "Game",
  "description": "tests"
}

### update photo
PUT localhost:8081/channel/updatePhoto/191d4771-0dbb-43ae-ac9a-e9dd647a3f26/c0056575-5cf7-4e72-adf4-996b577be2a0
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5MjY0OTIsImVtYWlsIjoiamFtb2wzOTA0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDkwMTI4OTIsImlzcyI6IllvdVR1YmUifQ.p3m_postr3wLoUlUYWaS-7Q8R_aUVh_r11-702RZQ_DszDQ_LEj_KM6ssFFM3dnKGXY-Wrbo8Fy1_f-rIFiIlA

### update banner
PUT localhost:8081/channel/updateBanner/191d4771-0dbb-43ae-ac9a-e9dd647a3f26/c0056575-5cf7-4e72-adf4-996b577be2a0
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5MjY0OTIsImVtYWlsIjoiamFtb2wzOTA0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDkwMTI4OTIsImlzcyI6IllvdVR1YmUifQ.p3m_postr3wLoUlUYWaS-7Q8R_aUVh_r11-702RZQ_DszDQ_LEj_KM6ssFFM3dnKGXY-Wrbo8Fy1_f-rIFiIlA


### get allBy paginations
GET localhost:8081/channel/getAllPagination?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5MzIxMjgsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkwMTg1MjgsImlzcyI6IllvdVR1YmUifQ.l2k-kf1qw-c83QyeX92vpJ1BNg5NX4psQWtUoJJegnAtPJRhxcEA5top8cHRoWQYgDr0oclR9sa0w9nbIudyIw

### get byId
GET localhost:8081/channel/getById/2fddcf56-af91-47a9-8c38-3ed21702f69e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyNzYxNzYsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MDkzNjI1NzYsImlzcyI6IllvdVR1YmUifQ.WoBz-pegi_u-0aAwQBLvofAymcoEDj_imSTILckNXGQ4NUpaMMKD_eUqbiQBeuTsm7phOvasNV5tvJaYDwMOyQ
### update Channel status
PUT localhost:8081/channel/changeStatus/191d4771-0dbb-43ae-ac9a-e9dd647a3f26
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDg5MjY0OTIsImVtYWlsIjoiamFtb2wzOTA0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDkwMTI4OTIsImlzcyI6IllvdVR1YmUifQ.p3m_postr3wLoUlUYWaS-7Q8R_aUVh_r11-702RZQ_DszDQ_LEj_KM6ssFFM3dnKGXY-Wrbo8Fy1_f-rIFiIlA
