### create video
POST localhost:8081/video/create
Content-Type:application/json

{
  "previewAttachId": "f30a45d8-cd00-4bc1-ae77-980eab3331af",
  "description": "test",
  "status": "PUBLIC",
  "title": "test title",
  "typeStatus": "SHORT",
  "attachId": "f30a45d8-cd00-4bc1-ae77-980eab3331af",
  "categoryId": 1

}