### create video like
POST localhost:8081/video_like/create_like
Content-Type: application/json

{
  "videoId": "1c3a5bf9-4278-4748-abd3-2aee91ec292f",
  "profileId": 5,
  "type": "LIKE"
}

### get list
GET localhost:8081/video_like/userLiked_list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDkyNzU2NTYsImVtYWlsIjoiamFtb2wzOTA0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE3MDkzNjIwNTYsImlzcyI6IllvdVR1YmUifQ.oTzhYHWshacVMWSRiLudUUS09cTqiglchhdXof2xFkCAlKzG_-ewrrrJLfC0TE3l7tBzv-nzJTznmYRqjbPlTA
